name: music-tracker
authors: [MiataBoy, Zortos]
version: '${project.version}'
main: org.commandomc.MusicTracker.SpotifyPlugin
api-version: 1.19

commands:
  auth:
    description: authenticate with spotify to display your status
    usage: /auth
  spotifySync:
    description: Refresh everyone's spotify song
    usage: /spotifySync
    permission: musictracker.sync
    permission-message: Only people with musictracker.sync can use this command.